version: "3.7"

services:
  api_backend_feminicidio:
    container_name: api_backend_feminicidio
    image: api_feminicidio
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: unless-stopped
    ports:
      - ${PORT_BACKEND}:${PORT_BACKEND}
    env_file: .env

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: feminicidio
    ports:
      - "5445:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    env_file: .env

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
