version: "3.7"

services:
  api_backend_feminicidio:
    container_name: api_backend_feminicidio_c
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - TZ=America/Manaus
      - DATABASE_URL=${DATABASE_URL_MANAUS}
      - CITY=manaus
      - HOUR_JOB=23
      - MINUTE_JOB=20
      - PORT_BACKEND=8000

  api_backend_feminicidio_porto_velho:
    container_name: api_backend_feminicidio_porto_velho_c
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file: .env
    environment:
      - TZ=America/Manaus
      - DATABASE_URL=${DATABASE_URL_PORTO_VELHO}
      - CITY=porto velho
      - HOUR_JOB=23
      - MINUTE_JOB=30
      - PORT_BACKEND=8001

  api_backend_feminicidio_rio_branco:
    container_name: api_backend_feminicidio_rio_branco_c
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: unless-stopped
    ports:
      - "8003:8002"
    env_file: .env
    environment:
      - TZ=America/Manaus
      - DATABASE_URL=${DATABASE_URL_RIO_BRANCO}
      - CITY=rio branco
      - HOUR_JOB=23
      - MINUTE_JOB=40
      - PORT_BACKEND=8002

  api_backend_feminicidio_rio_de_janeiro:
    container_name: api_backend_feminicidio_rio_de_janeiro_c
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: unless-stopped
    ports:
      - "8002:8003"
    env_file: .env
    environment:
      - TZ=America/Manaus
      - DATABASE_URL=${DATABASE_URL_RIO_DE_JANEIRO}
      - CITY=rio de janeiro
      - HOUR_JOB=23
      - MINUTE_JOB=50
      - PORT_BACKEND=8003

#   postgres:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: feminicidio
#     ports:
#       - "5445:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - postgres_network
#     env_file: .env

# volumes:
#   postgres_data:

# networks:
#   postgres_network:
#     driver: bridge