"""adicionando coluna cidade em vitimas

Revision ID: 177604bf28e4
Revises: e890e532c47f
Create Date: 2025-10-26 18:27:53.923105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177604bf28e4'
down_revision: Union[str, None] = 'e890e532c47f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vitimas', sa.Column('cidade', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vitimas', 'cidade')
    # ### end Alembic commands ###
